apiVersion: v1
kind: Service
metadata:
  name: nist-csf-mcp-server
  namespace: nist-csf
  labels:
    app.kubernetes.io/name: nist-csf-mcp-server
    app.kubernetes.io/component: service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  selector:
    app.kubernetes.io/name: nist-csf-mcp-server
---
apiVersion: v1
kind: Service
metadata:
  name: nist-csf-mcp-server-headless
  namespace: nist-csf
  labels:
    app.kubernetes.io/name: nist-csf-mcp-server
    app.kubernetes.io/component: headless-service
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: http
    port: 8080
    targetPort: http
    protocol: TCP
  selector:
    app.kubernetes.io/name: nist-csf-mcp-server